---
- name: Reload systemd and restart step-ca
  ansible.builtin.systemd:
    daemon_reload: true
    name: step-ca
    state: restarted

- name: Reload step-ca config
  ansible.builtin.command:
    cmd: systemctl kill -s HUP step-ca
  changed_when: true
