#!/usr/bin/env bash
# terraform-guard.sh — PreToolUse hook for Bash tool
# Enforces the terraform safety rules from sandbox-isolation.md as hard blocks.
# Input: JSON object on stdin with tool_input.command

set -euo pipefail

cmd=$(python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('tool_input',{}).get('command',''))" 2>/dev/null ||
echo "")

# Resolve current ENV and plan filename from .env.mk (generated by make configure)
ENVMK_FILE="$(dirname "$0")/../../.env.mk"
CURRENT_ENV="sandbox"
CURRENT_PLANFILE="sandbox.tfplan"
if [[ -f "${ENVMK_FILE}" ]]; then
    _env=$(grep -E '^ENV\s*:?=' "${ENVMK_FILE}" | head -1 | sed 's/.*:*=\s*//' | tr -d '[:space:]')
    _plan=$(grep -E '^TF_PLANFILE\s*:?=' "${ENVMK_FILE}" | head -1 | sed 's/.*:*=\s*//' | tr -d '[:space:]')
    CURRENT_ENV="${_env:-sandbox}"
    CURRENT_PLANFILE="${_plan:-${CURRENT_ENV}.tfplan}"
fi

# --- terraform apply ---

if [[ "$cmd" == *"terraform apply"* ]] && [[ "$cmd" != *".tfplan"* ]]; then
    echo "BLOCKED: bare 'terraform apply' detected."
    echo "Required workflow: terraform plan -out=<file>.tfplan && terraform apply <file>.tfplan"
    exit 2
fi

if [[ "${CURRENT_ENV}" != "sandbox" ]] && [[ "$cmd" == *"terraform apply ${CURRENT_PLANFILE}"* ]]; then
    echo "BLOCKED: applying a non-sandbox plan (${CURRENT_ENV}) is not permitted from the dev container."
    echo "Hand ${CURRENT_PLANFILE} to the operator for manual apply."
    exit 2
fi

# --- terraform destroy ---

if [[ "$cmd" == *"terraform destroy"* ]]; then
    echo "BLOCKED: terraform destroy is not permitted from the dev container."
    echo "To remove resources, use a targeted destroy plan:"
    echo "  terraform plan -destroy -var-file=${CURRENT_ENV}.tfvars -out=destroy.tfplan"
    echo "  terraform apply destroy.tfplan"
    echo "For non-sandbox resources, coordinate with the operator."
    exit 2
fi

# --- state manipulation ---

if [[ "$cmd" == *"terraform state rm"* ]]; then
    echo "BLOCKED: terraform state rm requires explicit operator approval."
    echo "State manipulation can cause resource orphaning and is prohibited from the dev container."
    exit 2
fi

if [[ "$cmd" == *"terraform state mv"* ]]; then
    echo "BLOCKED: terraform state mv requires explicit operator approval."
    exit 2
fi

if [[ "$cmd" == *"terraform force-unlock"* ]]; then
    echo "BLOCKED: terraform force-unlock requires explicit operator approval."
    echo "If a lock is stuck, verify no concurrent apply is running before unlocking."
    exit 2
fi

if [[ "$cmd" == *"terraform import"* ]]; then
    echo "BLOCKED: terraform import requires explicit operator instruction."
    echo "Importing resources can cause state drift if not carefully validated."
    exit 2
fi

exit 0