"""genconfig.emit.allowed_cidrs — render .devcontainer/squid/allowed-cidrs.conf."""

from ..helpers import resolve_network, validate_cidr


def gen_allowed_cidrs(cfg: dict, env: str) -> str:
    infra = cfg.get("infrastructure", {})
    networks = infra.get("networks", {})
    default_network = infra.get("default_network")
    p = infra.get("proxmox", {})
    nodes = infra.get("nodes", {})
    svcs = cfg.get("services", {}) or {}

    proxmox_cidr = f'{p.get("ip", "")}/32' if p.get("ip") else ""

    # Collect the set of network names actually used by deployed services
    used_network_names = set()
    for svc_name, svc in svcs.items():
        if not isinstance(svc, dict):
            continue
        if "ip" in svc:
            net_name = svc.get("network") or default_network
            resolve_network(svc, networks, default_network, svc_name)
            used_network_names.add(net_name)
        else:
            for subkey, sub in svc.items():
                if not isinstance(sub, dict) or "ip" not in sub:
                    continue
                net_name = sub.get("network") or default_network
                resolve_network(sub, networks, default_network, f"{svc_name}.{subkey}")
                used_network_names.add(net_name)

    lines = [
        f"# Generated by scripts/generate-configs.py from config/{env}.yml",
        f"# DO NOT EDIT — run `make configure` to regenerate.",
        f"# After changes, rebuild the container: make build",
        f"",
    ]
    seen = set()

    # Emit one CIDR per used network
    for net_name in sorted(used_network_names):
        if net_name not in networks:
            continue
        cidr = networks[net_name]["cidr"]
        validate_cidr(cidr, f"infrastructure.networks.{net_name}.cidr")
        if cidr and cidr not in seen:
            lines.append(cidr)
            seen.add(cidr)

    # Per-node IPs — one /32 per cluster node for Squid allowlist
    for node_name in sorted(nodes.keys()):
        node_ip = nodes[node_name].get("ip", "")
        if node_ip:
            node_cidr = f"{node_ip}/32"
            if node_cidr not in seen:
                lines.append(node_cidr)
                seen.add(node_cidr)

    # Proxmox /32 special case (unchanged)
    if proxmox_cidr and proxmox_cidr not in seen:
        lines.append(proxmox_cidr)
        seen.add(proxmox_cidr)

    return "\n".join(lines) + "\n"
