"""genconfig.emit.ansible_cfg — render ansible/ansible.cfg.

The agent-host facts (SSH key path, extra SSH args such as a proxy hop) come
from config's optional `agent:` section, so committed files stop encoding
WHERE the agent runs. Component roles resolve adjacent to their playbook;
roles_path lists only the core shared roles.

  agent:
    ssh_private_key: ~/.ssh/id_ed25519   # default
    ssh_extra_args: ""                   # appended to ssh_args (e.g. a ProxyCommand)
"""


_BASE_SSH_ARGS = (
    "-o StrictHostKeyChecking=accept-new -o ControlMaster=auto "
    "-o ControlPersist=10m -o ConnectTimeout=30 "
    "-o ServerAliveInterval=15 -o ServerAliveCountMax=3"
)


def gen_ansible_cfg(cfg: dict, env: str) -> str:
    agent = cfg.get("agent", {}) or {}
    ssh = cfg.get("ssh", {}) or {}
    default_user = ssh.get("default_user", "ubuntu")
    key_path = agent.get("ssh_private_key", "~/.ssh/id_ed25519")
    extra_args = (agent.get("ssh_extra_args") or "").strip()
    ssh_args = f"{_BASE_SSH_ARGS} {extra_args}".strip()

    return f"""\
# Generated by scripts/generate-configs.py from config/{env}.yml
# DO NOT EDIT — run `make configure` to regenerate. Agent-host facts (SSH key,
# extra ssh args) come from the config's agent: section.

[defaults]
inventory           = inventory/
roles_path          = roles/
collections_paths   = ~/.ansible/collections
remote_user         = {default_user}
private_key_file    = {key_path}
host_key_checking   = True
retry_files_enabled = False
stdout_callback     = ansible.builtin.default
callback_result_format = yaml

[privilege_escalation]
become        = True
become_method = sudo

[ssh_connection]
pipelining = True
ssh_args = {ssh_args}
"""
