"""genconfig.emit.env_mk — render .env.mk (Makefile-includable ENV/bucket vars)."""

import textwrap


def gen_env_mk(cfg: dict, env: str) -> str:
    t = cfg.get("terraform", {})
    bucket = t.get("state_bucket", f"tfstate-{env}")
    return textwrap.dedent(f"""\
        # Generated by scripts/generate-configs.py from config/{env}.yml
        # DO NOT EDIT — run `make configure` to regenerate.
        ENV         := {env}
        TF_BUCKET   := {bucket}
        TF_VARFILE  := {env}.tfvars
        TF_PLANFILE := {env}.tfplan
    """)
