"""genconfig.emit.envrc — render the non-secret portion of .envrc.

Emits CHANGE_ME placeholders for every secret each PRESENT component declares
in its manifest's env: section (presence in config, enabled or not — so
gen-secrets can pre-fill a service before it is switched on). The file-writing
path (helpers.atomic_write) smart-merges in any secrets the operator already
filled and never deletes a key it did not emit.

INTERIM couplings (capability s3.endpoint in phase 4): MINIO_ENDPOINT and the
AWS_CA_BUNDLE block are derived from services.minio here.
"""

import sys
import textwrap

from ..config import CHANGE_ME
from ..discovery import component_order, discover_components
from ..helpers import _strip_prefix


def gen_envrc(cfg: dict, env: str, components: dict | None = None) -> str:
    infra = cfg.get("infrastructure", {})
    p = infra.get("proxmox", {})
    svcs = cfg.get("services", {}) or {}
    m = svcs.get("minio", {})

    endpoint = (
        f'https://{p["ip"]}:{p.get("port", 8006)}'
        if p.get("ip") else CHANGE_ME
    )
    insecure = str(p.get("insecure", "true")).lower()
    minio_tls = m.get("tls", False)
    minio_fqdn = m.get("fqdn", "")
    if minio_tls and not minio_fqdn:
        print("ERROR: services.minio.tls is true but services.minio.fqdn is not set.", file=sys.stderr)
        sys.exit(1)
    if m.get("ip"):
        if minio_tls and minio_fqdn:
            minio_endpoint = f"https://{minio_fqdn}:{m.get('port', 9000)}"
        else:
            scheme = "https" if minio_tls else "http"
            minio_endpoint = f'{scheme}://{_strip_prefix(m["ip"])}:{m.get("port", 9000)}'
    else:
        minio_endpoint = CHANGE_ME

    parts = [textwrap.dedent(f"""\
        # Generated by scripts/generate-configs.py from config/{env}.yml
        # DO NOT EDIT the non-secret values — run `make configure` to regenerate.
        # Fill in all CHANGE_ME secrets below manually. This is the single source for all secrets.
        _envrc_dir="$(cd "$(dirname "${{BASH_SOURCE[0]:-$0}}")" && pwd)"

        # Proxmox — endpoint auto-populated from config, token is a secret
        export PROXMOX_VE_ENDPOINT="{endpoint}"
        export PROXMOX_VE_INSECURE="{insecure}"
        export PROXMOX_VE_API_TOKEN="{CHANGE_ME}"  # e.g. terraform@pve!claude-{env}=<uuid>
    """)]

    # Per-component secret sections — from each manifest's env: block, for every
    # component PRESENT in config (enabled or not).
    components = components or discover_components()
    present = [c for c in components.values() if c["manifest"]["name"] in svcs]
    for comp in sorted(present, key=component_order):
        manifest = comp["manifest"]
        env_block = manifest.get("env") or {}
        env_vars = env_block.get("vars") or []
        if not env_vars:
            continue
        section = [f"\n# {env_block.get('header', manifest['name'] + ' secrets')}"]
        for var in env_vars:
            comment = f"  # {var['comment']}" if var.get("comment") else ""
            section.append(f'export {var["name"]}="{CHANGE_ME}"{comment}')
        parts.append("\n".join(section) + "\n")

        if manifest["name"] == "minio":
            # INTERIM: derived state-backend endpoint (capability s3.endpoint later).
            parts.append(textwrap.dedent(f"""\

                # MinIO endpoint — derived from config; Terraform S3 backend + tooling
                export MINIO_ENDPOINT="{minio_endpoint}"
            """))

    if minio_tls:
        # The S3 client (Terraform's AWS SDK) must trust the internal CA that
        # signed the MinIO server cert, or state access fails. AWS_CA_BUNDLE
        # points the SDK at the exported root CA (controller-local staging).
        parts.append(textwrap.dedent("""\

            # Internal CA trust for the HTTPS MinIO state backend (minio.tls: true).
            # Requires .pki/root_ca.crt to exist (PKI deployed).
            export AWS_CA_BUNDLE="${_envrc_dir}/.pki/root_ca.crt"
        """))

    parts.append(textwrap.dedent("""\

        # Internal CA trust — uncomment after PKI setup (.pki/root_ca.crt exists)
        # Go (Terraform) and curl pick this up; no container rebuild needed.
        # export SSL_CERT_FILE="${_envrc_dir}/.pki/root_ca.crt"

        # Operator-local additions — never templated or merged by `make configure`.
        # Machine-specific env and extra secrets belong in .envrc.local (gitignored).
        if [ -f "${_envrc_dir}/.envrc.local" ]; then
            . "${_envrc_dir}/.envrc.local"
        fi
        unset _envrc_dir
    """))

    return "".join(parts)
