"""genconfig.emit.envrc — render the non-secret portion of .envrc.

Emits CHANGE_ME placeholders for every secret; the file-writing path
(helpers.atomic_write) smart-merges in any secrets the operator already filled.
"""

import sys
import textwrap

from ..config import CHANGE_ME
from ..helpers import _strip_prefix


def gen_envrc(cfg: dict, env: str) -> str:
    infra = cfg.get("infrastructure", {})
    p = infra.get("proxmox", {})
    svcs = cfg.get("services", {}) or {}
    m = svcs.get("minio", {})

    endpoint = (
        f'https://{p["ip"]}:{p.get("port", 8006)}'
        if p.get("ip") else CHANGE_ME
    )
    insecure = str(p.get("insecure", "true")).lower()
    minio_tls = m.get("tls", False)
    minio_fqdn = m.get("fqdn", "")
    if minio_tls and not minio_fqdn:
        print("ERROR: services.minio.tls is true but services.minio.fqdn is not set.", file=sys.stderr)
        sys.exit(1)
    if m.get("ip"):
        if minio_tls and minio_fqdn:
            minio_endpoint = f"https://{minio_fqdn}:{m.get('port', 9000)}"
        else:
            scheme = "https" if minio_tls else "http"
            minio_endpoint = f'{scheme}://{_strip_prefix(m["ip"])}:{m.get("port", 9000)}'
    else:
        minio_endpoint = CHANGE_ME

    splunk = svcs.get("splunk", {})

    parts = [textwrap.dedent(f"""\
        # Generated by scripts/generate-configs.py from config/{env}.yml
        # DO NOT EDIT the non-secret values — run `make configure` to regenerate.
        # Fill in all CHANGE_ME secrets below manually. This is the single source for all secrets.

        # Proxmox — endpoint auto-populated from config, token is a secret
        export PROXMOX_VE_ENDPOINT="{endpoint}"
        export PROXMOX_VE_INSECURE="{insecure}"
        export PROXMOX_VE_API_TOKEN="{CHANGE_ME}"  # e.g. terraform@pve!claude-{env}=<uuid>

        # MinIO root credentials — used by Ansible (minio role) and bootstrap-minio.sh
        export MINIO_ROOT_USER="{CHANGE_ME}"      # MinIO root/admin username
        export MINIO_ROOT_PASSWORD="{CHANGE_ME}"  # MinIO root/admin password

        # MinIO scoped key — endpoint auto-populated; keys from: bash scripts/bootstrap-minio.sh {env}
        export MINIO_ENDPOINT="{minio_endpoint}"
        export MINIO_ACCESS_KEY="{CHANGE_ME}"  # terraform-{env} scoped key (read/write tfstate-{env} only)
        export MINIO_SECRET_KEY="{CHANGE_ME}"  # terraform-{env} scoped secret

        # step-ca PKI passwords — used by Ansible pki-setup.yml playbook
        export STEP_CA_ROOT_PASSWORD="{CHANGE_ME}"          # password protecting the Root CA private key
        export STEP_CA_ISSUING_PASSWORD="{CHANGE_ME}"       # password protecting the Issuing CA private key
        export STEP_CA_LXC_ROOT_PASSWORD="{CHANGE_ME}"      # root account password for the Issuing CA LXC
        export STEP_CA_PROVISIONER_PASSWORD="{CHANGE_ME}"   # JWK provisioner password (used by minio TLS setup)

        # PowerDNS API keys — used by Ansible dns-setup.yml / dns-dist-setup.yml playbooks
        export PDNS_AUTH_API_KEY="{CHANGE_ME}"          # Auth webserver/API key
        export PDNS_RECURSOR_API_KEY="{CHANGE_ME}"      # Recursor webserver/API key
        export PDNS_DNSDIST_API_KEY="{CHANGE_ME}"       # DNSdist webserver/API key

        # Nexus credentials — used by Ansible nexus-setup.yml playbook
        export NEXUS_ADMIN_PASSWORD="{CHANGE_ME}"   # Nexus admin account password
        export NEXUS_READER_PASSWORD="{CHANGE_ME}"  # nexus-reader account (read-only APT/artifact access)

        # OTel Collector credentials — used by Ansible log-server-setup.yml playbook
        export OTELCOL_MINIO_ACCESS_KEY="{CHANGE_ME}"  # write-scoped key for otelcol-logs bucket
        export OTELCOL_MINIO_SECRET_KEY="{CHANGE_ME}"  # write-scoped secret
    """)]

    if splunk:
        parts.append(textwrap.dedent(f"""\

            # Splunk credentials — used by Ansible splunk-setup.yml playbook
            export SPLUNK_ADMIN_PASSWORD="{CHANGE_ME}"  # admin account password
            export SPLUNK_HEC_TOKEN="{CHANGE_ME}"       # HEC token UUID (generate with uuidgen); reuse in OTel config
            export SPLUNK_MCP_PASSWORD="{CHANGE_ME}"    # mcp service account password
        """))

    if minio_tls:
        # MinIO serves the TF state backend over HTTPS (minio.tls: true). The S3
        # client (Terraform's AWS SDK) must trust the internal CA that signed the
        # MinIO server cert, or `terraform init`/state access fails. AWS_CA_BUNDLE
        # points the SDK at the exported root CA. Emitted (uncommented) only when
        # minio.tls is true so the loop's own init survives the HTTPS backend.
        parts.append(textwrap.dedent("""\

            # Internal CA trust for the HTTPS MinIO state backend (minio.tls: true).
            # Terraform's S3 client reads AWS_CA_BUNDLE to validate the MinIO server
            # cert against the internal root CA. Requires .pki/root_ca.crt to exist
            # (PKI deployed). Go/curl also honour SSL_CERT_FILE below if uncommented.
            export AWS_CA_BUNDLE=/workspace/.pki/root_ca.crt
        """))

    parts.append(textwrap.dedent("""\

        # Internal CA trust — uncomment after PKI setup (.pki/root_ca.crt exists)
        # Go (Terraform) and curl pick this up; no container rebuild needed.
        # export SSL_CERT_FILE=/workspace/.pki/root_ca.crt
    """))

    return "".join(parts)
