"""genconfig.emit.inventory — render ansible/inventory/hosts.yml.

Holds the cross-service derivations that the per-output-artifact boundary keeps
in ONE pass (see scripts/CLAUDE.md "Cross-service couplings"):
  - log_server reads services.minio (otelcol_minio_endpoint) and services.splunk
    (otelcol_splunk_hec_*).
  - dns.dist reads its network CIDR + client_cidrs (pdns_dnsdist_acl_cidrs) and
    services.log_server.ip (dns_collector syslog wiring).
  - _derive_dns_records feeds both common_internal_hosts (/etc/hosts) and the
    dns_auth A-records.
"""

import sys

from ..helpers import _derive_dns_records, _strip_prefix, resolve_network, validate_domain_name
from ..validation import validate_nexus_apt_proxy_repos, validate_nexus_raw_hosted_repos


def gen_inventory(cfg: dict, env: str) -> str:
    hosts_cfg = cfg.get("hosts", {}) or {}
    ssh = cfg.get("ssh", {})
    svcs = cfg.get("services", {}) or {}
    default_user = ssh.get("default_user", "ubuntu")
    domain_name = cfg.get("domain_name", "")
    validate_domain_name(domain_name, "domain_name")
    infra = cfg.get("infrastructure", {})
    networks = infra.get("networks", {})
    default_network = infra.get("default_network")

    # nexus_apt_proxy — base Nexus URL emitted into all.vars so roles can construct
    # per-repo URLs (e.g. {{ nexus_apt_proxy }}/repository/apt-proxy-trixie/).
    # Phase 2 (tls: false): http://<ip>:8081  — plain HTTP, before PKI is deployed.
    # Phase 5+ (tls: true): https://<fqdn>:8443 — nginx TLS, requires fqdn to be set.
    # Empty string when Nexus is not enabled — roles skip proxy config when falsy.
    nexus_svc = svcs.get("nexus", {})
    nexus_enabled = bool(nexus_svc.get("enabled", False))
    nexus_ip = _strip_prefix(nexus_svc.get("ip", "")) if nexus_enabled else ""
    nexus_tls = bool(nexus_svc.get("tls", False)) if nexus_enabled else False
    nexus_fqdn_raw = nexus_svc.get("fqdn", "") if nexus_enabled else ""
    if nexus_tls and nexus_fqdn_raw:
        nexus_apt_proxy = f"https://{nexus_fqdn_raw}:8443"
    elif nexus_ip:
        nexus_apt_proxy = f"http://{nexus_ip}:8081"
    else:
        nexus_apt_proxy = ""

    lines = [
        f"# Generated by scripts/generate-configs.py from config/{env}.yml",
        f"# DO NOT EDIT — add hosts to config/{env}.yml and run `make configure`.",
        f"",
        f"all:",
        f"  vars:",
        f"    ansible_user: {default_user}",
    ]
    if domain_name:
        lines.append(f"    domain_name: {domain_name}")
    lines.append(f"    nexus_apt_proxy: \"{nexus_apt_proxy}\"")
    # nexus_fallback — phase-keyed run parameter, NOT per-env config. Shared
    # default 'fail' is fail-safe: when Nexus is unreachable a deploy aborts with
    # a clear message rather than silently chasing upstream (correct in a
    # firewalled steady state, where upstream is unreachable anyway). Bootstrap
    # tooling (scripts/loop/run.sh cold rebuild, the prod scaffolding runbook)
    # overrides to 'upstream' with `-e nexus_fallback=upstream`, since Nexus does
    # not exist yet at the PKI phase. See docs/design/apt-fallback-policy.md.
    lines.append(f"    nexus_fallback: \"fail\"")
    log_server_svc = svcs.get("log_server", {})
    log_server_ip_for_all = _strip_prefix(log_server_svc.get("ip", "")) if log_server_svc.get("enabled", False) else ""
    if log_server_ip_for_all:
        lines.append(f'    common_log_server_address: "{log_server_ip_for_all}"')
    # Internal service FQDN → IP map for /etc/hosts (the common role writes these).
    # Decouples cold-start TLS from the internal DNS server: services can reach
    # ca.<domain>, nexus.<domain>, etc. before DNSdist is deployed. Reuses the
    # DNS A-record derivation, so it honours dns_name overrides and dns: false.
    if domain_name:
        internal_hosts = _derive_dns_records(svcs)
        if internal_hosts:
            lines.append(f"    common_internal_hosts:")
            for rec in internal_hosts:
                lines.append(f'      - {{ip: "{rec["ip"]}", fqdn: "{rec["name"]}.{domain_name}"}}')
    lines.append(f"  children:")

    has_content = bool(svcs) or any(v for v in hosts_cfg.values())

    if not has_content:
        lines.append(f"    {env}:")
        lines.append(f"      hosts: {{}}")
    else:
        # Auto-derive inventory groups from services:
        # - Flat service (has top-level 'ip'): one group, one host
        # - Nested service (sub-dicts each with 'ip'): one group per sub-host
        for svc_name, svc in svcs.items():
            if not isinstance(svc, dict):
                continue
            if "ip" in svc:
                # Flat service (e.g. minio)
                hostname = svc.get("hostname", f"{svc_name}-server")
                host_ip  = _strip_prefix(svc["ip"])
                lines.append(f"    {svc_name}:")
                # minio: propagate TLS config as group vars so role defaults stay deployment-agnostic
                if svc_name == "minio":
                    minio_tls = svc.get("tls", False)
                    minio_fqdn = svc.get("fqdn", "")
                    # minio_ca_url: use domain-based CA URL — DNS is required to be deployed
                    # before the TLS phase, so ca.<domain> is resolvable by this point.
                    # IP-based URL cannot work because the CA cert has only DNS SANs.
                    lines.append(f"      vars:")
                    lines.append(f"        minio_tls_enabled: {str(bool(minio_tls)).lower()}")
                    if minio_fqdn:
                        lines.append(f"        minio_domain: {minio_fqdn}")
                    if domain_name:
                        lines.append(f"        minio_ca_url: https://ca.{domain_name}")
                    # Cert SAN coupling: the MinIO server cert must validate for
                    # whatever host MINIO_ENDPOINT uses. .envrc points the endpoint
                    # at the FQDN (https://{fqdn}:{port}) when tls:true, so the FQDN
                    # is the primary SAN (minio_domain); the bare IP is added as a
                    # secondary SAN so IP-addressed access (and the loop's own
                    # state-backend reachability checks) still validate.
                    lines.append(f"        minio_endpoint_ip: {host_ip}")
                # nexus: propagate domain, CA URL, and APT proxy repo list
                elif svc_name == "nexus":
                    nexus_fqdn = svc.get("fqdn", "")
                    nexus_tls = svc.get("tls", False)
                    apt_proxy_repos = svc.get("apt_proxy_repos", [])
                    if nexus_enabled:
                        validate_nexus_apt_proxy_repos(apt_proxy_repos, "services.nexus.apt_proxy_repos")
                    lines.append(f"      vars:")
                    lines.append(f"        nexus_tls_enabled: {str(bool(nexus_tls)).lower()}")
                    if nexus_fqdn:
                        lines.append(f"        nexus_domain: {nexus_fqdn}")
                    if domain_name:
                        lines.append(f"        nexus_ca_url: https://ca.{domain_name}")
                    if apt_proxy_repos:
                        lines.append(f"        nexus_apt_proxy_repos:")
                        for repo in apt_proxy_repos:
                            entry = f'{{name: "{repo["name"]}", remote_url: "{repo["remote_url"]}", distribution: "{repo["distribution"]}"'
                            if repo.get("flat") is True:
                                entry += ", flat: true"
                            entry += "}"
                            lines.append(f"          - {entry}")
                    else:
                        lines.append(f"        nexus_apt_proxy_repos: []")
                    raw_hosted_repos = svc.get("raw_hosted_repos", [])
                    if nexus_enabled and raw_hosted_repos:
                        validate_nexus_raw_hosted_repos(raw_hosted_repos, "services.nexus.raw_hosted_repos")
                    if raw_hosted_repos:
                        lines.append(f"        nexus_raw_hosted_repos:")
                        for repo in raw_hosted_repos:
                            lines.append(f'          - {{name: "{repo["name"]}"}}'  )
                    else:
                        lines.append(f"        nexus_raw_hosted_repos: []")
                elif svc_name == "log_server":
                    minio_svc = svcs.get("minio", {})
                    minio_tls = minio_svc.get("tls", False)
                    minio_fqdn = minio_svc.get("fqdn", "")
                    minio_ip = _strip_prefix(minio_svc.get("ip", ""))
                    minio_port = minio_svc.get("port", 9000)
                    if minio_tls and minio_fqdn:
                        otelcol_endpoint = f"https://{minio_fqdn}:{minio_port}"
                    elif minio_ip:
                        otelcol_endpoint = f"http://{minio_ip}:{minio_port}"
                    else:
                        otelcol_endpoint = ""
                    splunk_svc = svcs.get("splunk", {})
                    splunk_ip = _strip_prefix(splunk_svc.get("ip", ""))
                    splunk_hec_port = splunk_svc.get("hec_port", 8088)
                    # Splunk HEC sink only when Splunk is ENABLED with an IP.
                    # Splunk is deprecation-planned; default sink is MinIO (awss3).
                    splunk_hec_on = bool(splunk_svc.get("enabled", False)) and bool(splunk_ip)
                    if otelcol_endpoint:
                        lines.append(f"      vars:")
                        lines.append(f"        otelcol_minio_endpoint: \"{otelcol_endpoint}\"")
                        lines.append(f"        otelcol_splunk_hec_enabled: {str(splunk_hec_on).lower()}")
                        if splunk_hec_on:
                            lines.append(f"        otelcol_splunk_hec_url: \"http://{splunk_ip}:{splunk_hec_port}\"")
                    else:
                        print(
                            "ERROR: services.log_server is present but otelcol_minio_endpoint "
                            "cannot be derived — set services.minio.ip (or services.minio.fqdn "
                            "when tls: true) in config/<env>.yml and re-run make configure.",
                            file=sys.stderr,
                        )
                        sys.exit(1)
                elif svc_name == "splunk":
                    splunk_cfg = svc
                    splunk_tls = splunk_cfg.get("tls", False)
                    splunk_fqdn = splunk_cfg.get("fqdn", "")
                    ca_url = f"https://ca.{domain_name}" if domain_name else ""
                    lines.append(f"      vars:")
                    lines.append(f"        splunk_tls_enabled: {str(bool(splunk_tls)).lower()}")
                    if splunk_fqdn:
                        lines.append(f"        splunk_domain: {splunk_fqdn}")
                    if ca_url:
                        lines.append(f"        splunk_ca_url: {ca_url}")
                lines.append(f"      hosts:")
                lines.append(f"        {hostname}:")
                lines.append(f"          ansible_host: {host_ip}")
                if "ansible_user" in svc:
                    lines.append(f"          ansible_user: {svc['ansible_user']}")
            else:
                # Nested service (e.g. pki with root_ca / issuing_ca sub-hosts)
                for subkey, sub in svc.items():
                    if not isinstance(sub, dict) or "ip" not in sub:
                        continue
                    group    = f"{svc_name}_{subkey}"
                    hostname = sub.get("hostname", subkey)
                    host_ip  = _strip_prefix(sub["ip"])
                    lines.append(f"    {group}:")
                    # NOTE: each group may emit at most one `vars:` block.
                    # If a group needs additional vars in the future, extend the
                    # existing block here rather than adding a second `vars:` key
                    # (duplicate YAML mapping keys produce invalid inventory).
                    if group == "dns_dist":
                        auth_sub = svc.get("auth", {})
                        recursor_ip = _strip_prefix(auth_sub.get("ip", ""))
                        dist_net = resolve_network(sub, networks, default_network, "dns.dist")
                        network_cidr = dist_net["cidr"]
                        client_cidrs = sub.get("client_cidrs", [])
                        seen_cidrs: list[str] = []
                        for cidr in [network_cidr] + list(client_cidrs):
                            if cidr not in seen_cidrs:
                                seen_cidrs.append(cidr)
                        lines.append(f"      vars:")
                        lines.append(f"        pdns_recursor_address: {recursor_ip}")
                        lines.append(f"        pdns_dnsdist_acl_cidrs:")
                        for cidr in seen_cidrs:
                            lines.append(f'          - "{cidr}"')
                        log_server_ip = _strip_prefix(svcs.get("log_server", {}).get("ip", ""))
                        # When log_server is present, automatically wire dns_dist → log_server syslog pipeline.
                        if log_server_ip:
                            lines.append(f'        dns_collector_syslog_endpoint: "{log_server_ip}"')
                            lines.append(f"        pdns_dnsdist_dnstap_enabled: true")
                    if group == "dns_auth":
                        _dns_records = _derive_dns_records(cfg.get("services", {}))
                        lines.append(f"      vars:")
                        if _dns_records:
                            lines.append(f"        dns_records:")
                            for r in _dns_records:
                                lines.append(f'          - {{name: "{r["name"]}", ip: "{r["ip"]}", ttl: {r["ttl"]}}}')
                        else:
                            lines.append(f"        dns_records: []")
                    lines.append(f"      hosts:")
                    lines.append(f"        {hostname}:")
                    lines.append(f"          ansible_host: {host_ip}")
                    if "ansible_user" in sub:
                        lines.append(f"          ansible_user: {sub['ansible_user']}")

        # Manual/ad-hoc hosts
        for group, members in hosts_cfg.items():
            lines.append(f"    {group}:")
            if not members:
                lines.append(f"      hosts: {{}}")
            else:
                lines.append(f"      hosts:")
                for hostname, hostvars in (members or {}).items():
                    lines.append(f"        {hostname}:")
                    for k, v in (hostvars or {}).items():
                        lines.append(f"          {k}: {v}")

    return "\n".join(lines) + "\n"
