"""genconfig.emit.pki_group_vars — render group_vars/pki_root_ca + pki_issuing_ca."""

import textwrap


def gen_pki_group_vars(cfg: dict, env: str) -> tuple[str, str]:
    """Return (root_ca_vars_content, issuing_ca_vars_content) for PKI group_vars files."""
    svcs = cfg.get("services", {}) or {}
    pki = svcs.get("pki", {}) or {}
    domain_name = cfg.get("domain_name", "")

    root_ca = pki.get("root_ca", {}) or {}
    issuing_ca = pki.get("issuing_ca", {}) or {}

    root_ca_name = root_ca.get("ca_name", "Homelab Root CA")
    issuing_ca_name = issuing_ca.get("ca_name", "Homelab Issuing CA")
    issuing_ca_dns = f"ca.{domain_name}" if domain_name else "ca.example.com"

    root_vars = textwrap.dedent(f"""\
        # Generated by scripts/generate-configs.py from config/{env}.yml
        # DO NOT EDIT — run `make configure` to regenerate.
        step_ca_root_ca_name: "{root_ca_name}"
    """)

    issuing_vars = textwrap.dedent(f"""\
        # Generated by scripts/generate-configs.py from config/{env}.yml
        # DO NOT EDIT — run `make configure` to regenerate.
        step_ca_issuing_ca_name: "{issuing_ca_name}"
        step_ca_issuing_ca_dns: "{issuing_ca_dns}"
        step_ca_issuing_ca_address: ":443"
    """)

    return root_vars, issuing_vars
