"""genconfig.emit.tfvars — render terraform/<env>.tfvars.

Emits shared infrastructure values plus a single `services` map (one entry per
enabled component instance with kind vm|lxc). The Terraform root fans two
static module blocks over that map — adding a service is a component-manifest
change, never a new module block. Sizing and lifecycle options come from each
component's manifest (instances.<i>.resources / .options), overridable per-env
via services.<name>.resources in config.
"""

import sys

from ..discovery import (
    component_order,
    discover_components,
    enabled_components,
    instance_config,
    instance_tf_key,
)
from ..helpers import _hcl_str, resolve_network, validate_cidr

# Canonical field order inside a services-map entry (byte-stable output).
_OPTION_ORDER = [
    "started", "start_on_boot", "agent_enabled", "cpu_type",
    "os_type", "unprivileged", "nesting", "data_disk_size", "data_disk_path",
]


def _hcl_val(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if v is None:
        return "null"
    return f'"{v}"'


def _service_entry(tf_key: str, inst: dict, blk: dict, networks: dict,
                   default_network, label: str, env_resources: dict) -> list[str]:
    """Render one services-map entry as indented HCL lines."""
    kind = inst["kind"]
    addr = blk.get("ip", "")
    validate_cidr(addr, f"services.{label}.ip")
    net = resolve_network(blk, networks, default_network, label)

    id_field = "vm_id" if kind == "vm" else "ct_id"
    if id_field not in blk:
        sys.exit(f"Config error: 'services.{label}' is missing required '{id_field}:'.")
    if not blk.get("hostname"):
        sys.exit(f"Config error: 'services.{label}' has no hostname (config or manifest default).")

    resources = dict(inst.get("resources") or {})
    resources.update(env_resources or {})  # per-env override (decision 7)

    pairs = [
        ("kind", kind),
        ("node", blk["node"]),
        ("id", blk[id_field]),
        ("name", blk["hostname"]),
        ("bridge", net["bridge"]),
        ("ipv4_address", addr),
        ("ipv4_gateway", net["gateway"]),
    ]
    for src, dst in (("cores", "cores"), ("memory_mb", "memory_mb"),
                     ("disk_gb", "disk_size_gb"), ("swap_mb", "swap_mb")):
        if src in resources:
            pairs.append((dst, resources[src]))
    options = inst.get("options") or {}
    for field in _OPTION_ORDER:
        if field in options:
            pairs.append((field, options[field]))
    if kind == "vm":
        if "cloud_init_template_id" not in blk:
            sys.exit(
                f"Config error: 'services.{label}.cloud_init_template_id' is required "
                f"for VM instances (the template VMID to clone)."
            )
        pairs.append(("clone_template_id", blk["cloud_init_template_id"]))

    width = max(len(k) for k, _ in pairs)
    lines = [f"  {tf_key} = {{"]
    lines += [f"    {k.ljust(width)} = {_hcl_val(v)}" for k, v in pairs]
    lines.append("  }")
    return lines


def gen_tfvars(cfg: dict, env: str, components: dict | None = None) -> str:
    infra = cfg.get("infrastructure", {})
    networks = infra["networks"]
    default_network = infra.get("default_network")
    s = infra.get("storage", {})
    t = cfg.get("terraform", {})
    ssh = cfg.get("ssh", {})

    pool_id = t.get("pool_id", "")
    ssh_key = ssh.get("public_key", "")

    # Widest key in this block: cloudinit_datastore_id (22 chars) — pad all to column 23
    lines = [
        f"# Generated by scripts/generate-configs.py from config/{env}.yml",
        f"# DO NOT EDIT — run `make configure` to regenerate.",
        f"",
        f'pool_id                = "{pool_id}"',
        f'datastore_id           = "{s.get("datastore_id", "local-lvm")}"',
        f'cloudinit_datastore_id = "{s.get("cloudinit_datastore_id", "local")}"',
        f'ssh_public_key         = {_hcl_str(ssh_key)}',
    ]

    # lxc_template_file_id — global, read from infrastructure.storage
    lxc_tmpl = s.get("lxc_template_file_id", "")
    if lxc_tmpl:
        lines += [
            f"",
            f'lxc_template_file_id = {_hcl_str(lxc_tmpl)}',
        ]

    dns_server = infra.get("dns_server", "").strip()
    dns_servers_hcl = f'["{dns_server}"]' if dns_server else "[]"
    lines += [
        f"",
        f"# DNS resolver injected into all LXC/VM initialization blocks",
        f'dns_servers = {dns_servers_hcl}',
    ]

    components = components or discover_components()
    enabled = enabled_components(components, cfg)

    entry_blocks: list[str] = []
    for comp in sorted(enabled.values(), key=component_order):
        manifest = comp["manifest"]
        name = manifest["name"]
        instances = manifest["instances"]
        single = len(instances) == 1
        for iname, inst in instances.items():
            if inst["kind"] == "none":
                continue  # out-of-TF-graph (bootstrap-provisioned)
            blk = instance_config(cfg, comp, iname)
            tf_key = instance_tf_key(name, iname, inst, single)
            label = name if single else f"{name}.{iname}"
            env_resources = blk.get("resources") or {}
            entry_blocks += _service_entry(
                tf_key, inst, blk, networks, default_network, label, env_resources
            )

    lines += [
        f"",
        f"# Terraform-managed guests — one entry per enabled component instance",
        f"# (kind: vm | lxc). Sizing comes from each component's manifest, with",
        f"# per-env overrides via services.<name>.resources in config.",
    ]
    if entry_blocks:
        lines.append("services = {")
        lines += entry_blocks
        lines.append("}")
    else:
        lines.append("services = {}")

    return "\n".join(lines) + "\n"
