"""genconfig.emit.tfvars — render terraform/<env>.tfvars.

Emits shared infrastructure values plus a single `services` map (one entry per
enabled service). The Terraform root fans two static module blocks (vm / lxc)
over that map — adding a service is a generator change, never a new module
block. Resource sizing lives in _SERVICE_SPECS until component manifests own
it (phase 2 of the component refactor).
"""

import sys

from ..helpers import _hcl_str, resolve_network, validate_cidr

# Per-service kind + sizing + lifecycle spec. Only values that differ from the
# `services` variable's typed-object defaults (terraform/variables.tf) are
# listed — omitted fields fall through to those defaults at plan time.
_SERVICE_SPECS = {
    "root_ca": {
        "kind": "vm",
        # Offline root CA: created stopped, never autostarts, no guest agent.
        "started": False,
        "start_on_boot": False,
        "agent_enabled": False,
    },
    "issuing_ca": {"kind": "lxc"},
    "dns_auth": {"kind": "lxc"},
    "dns_dist": {"kind": "lxc"},
    "nexus": {
        "kind": "lxc",
        "cores": 2,
        "memory_mb": 8192,
        "data_disk_size": "20G",
        "data_disk_path": "/mnt/nexus-data",
    },
    "log_server": {"kind": "lxc", "memory_mb": 1024, "disk_size_gb": 100},
    "splunk": {
        "kind": "vm",
        "cores": 4,
        "cpu_type": "x86-64-v3",
        "memory_mb": 12288,
        "disk_size_gb": 150,
        "start_on_boot": False,
    },
}

# Fallback hostnames when config omits `hostname:` (match the pre-map layout).
_DEFAULT_NAMES = {
    "root_ca": "root-ca",
    "issuing_ca": "issuing-ca",
    "dns_auth": "dns-auth",
    "dns_dist": "dns-dist",
    "nexus": "nexus-server",
    "log_server": "log-server",
    "splunk": "splunk",
}

_DEFAULT_IDS = {
    "root_ca": 201,
    "issuing_ca": 202,
    "dns_auth": 103,
    "dns_dist": 104,
    "nexus": 205,
    "log_server": 206,
    "splunk": 207,
}


def _hcl_val(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if v is None:
        return "null"
    return f'"{v}"'


def _service_entry(svc_key: str, svc: dict, networks: dict, default_network, label: str) -> list[str]:
    """Render one services-map entry as indented HCL lines."""
    spec = _SERVICE_SPECS[svc_key]
    addr = svc.get("ip", "")
    validate_cidr(addr, f"services.{label}.ip")
    net = resolve_network(svc, networks, default_network, label)

    id_field = "vm_id" if spec["kind"] == "vm" else "ct_id"
    pairs = [
        ("kind", spec["kind"]),
        ("node", svc["node"]),
        ("id", svc.get(id_field, _DEFAULT_IDS[svc_key])),
        ("name", svc.get("hostname", _DEFAULT_NAMES[svc_key])),
        ("bridge", net["bridge"]),
        ("ipv4_address", addr),
        ("ipv4_gateway", net["gateway"]),
    ]
    for field in (
        "cores", "memory_mb", "disk_size_gb", "started", "start_on_boot",
        "clone_template_id", "agent_enabled", "cpu_type",
        "os_type", "swap_mb", "unprivileged", "nesting",
        "data_disk_size", "data_disk_path",
    ):
        if field in spec:
            pairs.append((field, spec[field]))
    if spec["kind"] == "vm":
        pairs.append(("clone_template_id", svc["cloud_init_template_id"]))

    width = max(len(k) for k, _ in pairs)
    lines = [f"  {svc_key} = {{"]
    lines += [f"    {k.ljust(width)} = {_hcl_val(v)}" for k, v in pairs]
    lines.append("  }")
    return lines


def gen_tfvars(cfg: dict, env: str) -> str:
    infra = cfg.get("infrastructure", {})
    networks = infra["networks"]
    default_network = infra.get("default_network")
    s = infra.get("storage", {})
    t = cfg.get("terraform", {})
    ssh = cfg.get("ssh", {})
    svcs = cfg.get("services", {})
    pki = svcs.get("pki", {})

    pool_id = t.get("pool_id", "")
    ssh_key = ssh.get("public_key", "")

    # Widest key in this block: cloudinit_datastore_id (22 chars) — pad all to column 23
    lines = [
        f"# Generated by scripts/generate-configs.py from config/{env}.yml",
        f"# DO NOT EDIT — run `make configure` to regenerate.",
        f"",
        f'pool_id                = "{pool_id}"',
        f'datastore_id           = "{s.get("datastore_id", "local-lvm")}"',
        f'cloudinit_datastore_id = "{s.get("cloudinit_datastore_id", "local")}"',
        f'ssh_public_key         = {_hcl_str(ssh_key)}',
    ]

    # lxc_template_file_id — global, read from infrastructure.storage
    lxc_tmpl = s.get("lxc_template_file_id", "")
    if lxc_tmpl:
        lines += [
            f"",
            f'lxc_template_file_id = {_hcl_str(lxc_tmpl)}',
        ]

    dns_server = infra.get("dns_server", "").strip()
    dns_servers_hcl = f'["{dns_server}"]' if dns_server else "[]"
    lines += [
        f"",
        f"# DNS resolver injected into all LXC/VM initialization blocks",
        f'dns_servers = {dns_servers_hcl}',
    ]

    # ------------------------------------------------------------------
    # services map — one entry per ENABLED service. A disabled service is
    # simply absent (the for_each fans out over what exists).
    # ------------------------------------------------------------------
    if pki and pki.get("issuing_ca", {}).get("lxc_template_file_id"):
        print("ERROR: lxc_template_file_id found in services.pki.issuing_ca. "
              "Move it to infrastructure.storage.lxc_template_file_id instead.", file=sys.stderr)
        sys.exit(1)

    entries: list[tuple[str, dict, str]] = []  # (map key, service dict, config label)
    if pki.get("enabled", False):
        root_ca = dict(pki.get("root_ca", {}))
        root_ca.setdefault("cloud_init_template_id", 9000)
        entries.append(("root_ca", root_ca, "pki.root_ca"))
        entries.append(("issuing_ca", pki.get("issuing_ca", {}), "pki.issuing_ca"))
    dns = svcs.get("dns", {})
    if dns.get("enabled", False):
        entries.append(("dns_auth", dns.get("auth", {}), "dns.auth"))
        entries.append(("dns_dist", dns.get("dist", {}), "dns.dist"))
    nexus = svcs.get("nexus", {})
    if nexus.get("enabled", False):
        entries.append(("nexus", nexus, "nexus"))
    log_server = svcs.get("log_server", {})
    if log_server.get("enabled", False):
        entries.append(("log_server", log_server, "log_server"))
    splunk = svcs.get("splunk", {})
    if splunk.get("enabled", False):
        if "cloud_init_template_id" not in splunk:
            sys.exit(
                "Config error: 'services.splunk.cloud_init_template_id' is required. "
                "Set it to the VMID of the Ubuntu 24.04 cloud-init template on your Proxmox host."
            )
        entries.append(("splunk", splunk, "splunk"))

    lines += [
        f"",
        f"# Terraform-managed guests — one entry per enabled service (kind: vm | lxc).",
        f"# Sizing/lifecycle defaults live in the services variable's typed object;",
        f"# per-service overrides come from the generator's spec table.",
    ]
    if entries:
        lines.append("services = {")
        for svc_key, svc, label in entries:
            lines += _service_entry(svc_key, svc, networks, default_network, label)
        lines.append("}")
    else:
        lines.append("services = {}")

    return "\n".join(lines) + "\n"
